TRUNCATE TABLE CUSTOMER;
truncate table TRANSACTION;

INSERT INTO CUSTOMER(CUSTOMER_ID,CUSTOMER_NAME)
values (1,'Adam');

INSERT INTO CUSTOMER(CUSTOMER_ID,CUSTOMER_NAME)
values (2,'Bob');

-- insert data for customer Adam
INSERT INTO TRANSACTION(TRANSACTION_ID,CUSTOMER_ID,TRANSACTION_DATE,AMOUNT)
VALUES (101,1,'2023-01-01',90);
INSERT INTO TRANSACTION(TRANSACTION_ID,CUSTOMER_ID,TRANSACTION_DATE,AMOUNT)
VALUES (102,1,'2022-12-01',120);
INSERT INTO TRANSACTION(TRANSACTION_ID,CUSTOMER_ID,TRANSACTION_DATE,AMOUNT)
VALUES (103,1,'2022-11-01',40);

-- insert data for customer bob
INSERT INTO TRANSACTION(TRANSACTION_ID,CUSTOMER_ID,TRANSACTION_DATE,AMOUNT)
VALUES (104,2,'2023-01-02',90);
INSERT INTO TRANSACTION(TRANSACTION_ID,CUSTOMER_ID,TRANSACTION_DATE,AMOUNT)
VALUES (105,2,'2022-12-02',50);
INSERT INTO TRANSACTION(TRANSACTION_ID,CUSTOMER_ID,TRANSACTION_DATE,AMOUNT)
VALUES (106,2,'2022-11-02',160);


